### ISSUE TITLE
Frontend Auth not working

### ISSUE THREAD

**Issue by federicoperroni** [johndavedecano/laragym#104]
I login with the credentials
admin@admin.com
password
But the frontend does not redirect me to the system home but rather makes a redirection to the same login.
By POSTMAN the API responds correctly:
"successes": true, ...

How can I start from the frontend?

**Comment by ramssesable** [comment]
I have the same issue

**Comment by abbasnake** [comment]
Same

**Comment by abbasnake** [comment]
Not sure where to get the initial default admin password but the one form DB returns an error - "The password must not be greater than 20 characters"

Perhaps the passwords in DB are stored in an encrypted format.

**Comment by johndavedecano** [comment]
the defaults are 
**email:** admin@admin
**password:** password

**Comment by johndavedecano** [comment]
Make you sure you also did seed
```
php artisan db:seed 
```
