### ISSUE TITLE
how to run it locally?

### ISSUE THREAD

**Issue by ivandgreat** [johndavedecano/laragym#13]
Hi i have follow the instructions, i might miss something.
Could you please help me how to run it on locally on my laptop.
I have receiving network error.

Thanks.

**Comment by johndavedecano** [comment]
probably you forgot to run the api

**Comment by ivandgreat** [comment]
I run it using npm start on folder frontend. And run as well the xampp at port 8080 but still unlucky to login.
Am i doing it right?
Pls need your help. Tnxs..

**Comment by johndavedecano** [comment]
run ```php artisan serve``` on the laravel side
