### ISSUE TITLE
Failed opening required '/var/www/laravel/bootstrap/../vendor/autoload.php'

### ISSUE THREAD

**Issue by mbrav** [johndavedecano/laragym#34]
Hi, just managed to get this running in docker using the `docker-compose.testing.yml` template,  but am getting the following error on http://localhost:8080

```
Warning: require(/var/www/laravel/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/laravel/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/laravel/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/laravel/bootstrap/autoload.php on line 17
```

For clarification, I changed nginx `ports: 8000:80` to `ports: 8080:80` in `docker-compose.testing.yml` as well as `APP_URL=http://localhost:8000` to `APP_URL=http://localhost:8080` in the `.env` file. Besides that, have not changed anything else. 

Any ideas? Thanks! This repo is a beast, thanks for sharing it.

![gym](https://user-images.githubusercontent.com/7410291/96118888-d7302d80-0ef4-11eb-954e-57ff96c1ed64.png)

**Comment by mbrav** [comment]
ok, so I ran `composer install` inside the the laragym_nginx/laragym_php docker container and that did the trick. But now I cannot connect to the database.
![2](https://user-images.githubusercontent.com/7410291/96123765-f8e0e300-0efb-11eb-82bf-04fbf083ac1a.png)

**Comment by mbrav** [comment]
Am now trying to execute the following command in `laragym_nginx/laragym_php` docker container:

`$ php artisan migrate`

But am getting an error similar to issue #11. But all my addresses are set to `127.0.0.1` instead of `localhost` in my `.env` file where I ran docker-compose.

![4](https://user-images.githubusercontent.com/7410291/96169684-37da5d00-0f2b-11eb-8c6d-63ca2e1bcfc4.png)

**Comment by BayasalB** [comment]
> Am now trying to execute the following command in `laragym_nginx/laragym_php` docker container:
> 
> `$ php artisan migrate`
> 
> But am getting an error similar to issue #11. But all my addresses are set to `127.0.0.1` instead of `localhost` in my `.env` file where I ran docker-compose.
> 
> ![4](https://user-images.githubusercontent.com/7410291/96169727-458fe280-0f2b-11eb-82e1-e9345fcf997b.png)

Hello, I’m having same issue, did u found the solution?
