### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by debasishbrahma** [johndavedecano/laragym#38]
![image](https://user-images.githubusercontent.com/20889798/106886679-2ac7c080-670a-11eb-9682-bd47fb4563d0.png)
Hi bro,

Not able to login into portal. can you help??

**Comment by javparra** [comment]
Hi bro, tell me a little about the environment and what you see in the log. I don't have the code for this app at this time

**Comment by debasishbrahma** [comment]
Dear,

Thanks for responding.

[cid:image002.png@01D6FB18.1109F360]
Server started. But it’s not allowing me to login. It’s showing a bad request 500. Can you help ?

Thanks in advance.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by debasishbrahma** [comment]
![image](https://user-images.githubusercontent.com/20889798/106887908-d6bddb80-670b-11eb-83ed-253a8148b475.png)
Hi mate,

see the log. Anything required ??

**Comment by javparra** [comment]
Check in the folder  /storage/logs tell me what it shows you. Error 500 is not very descriptive...

**Comment by debasishbrahma** [comment]
Hi mate,

I’m sharing you the file. Kindly check.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ahmedch1** [comment]
Please what is the first username credentials (admin)
Thanks in advance

**Comment by DOCTOR29** [comment]
what is the login credentials?? please

**Comment by johndavedecano** [comment]
> what is the login credentials?? please

i believe it is on the seeder files

**Comment by DOCTOR29** [comment]
> 
> 
> > what is the login credentials?? please
> 
> i believe it is on the seeder files

thank you :)
