### ISSUE TITLE
Laravel 10 - Files API

### ISSUE THREAD

**Issue by johndavedecano** [johndavedecano/laragym#81]
| Method | URI                               | Name                  | Action                                                         |
| ------ | --------------------------------- | --------------------- | -------------------------------------------------------------- |
| GET    | /api/files       | files.index   | App\Api\V1\Controllers\FileController@index            |
| POST   | /api/files                | files.store   | App\Api\V1\Controllers\FileController@store            |
| GET    | /api/files/{file} | files.show    | App\Api\V1\Controllers\FileController@show             |
| PUT    | /api/files/{file} | files.update  | App\Api\V1\Controllers\FileController@update           |
| DELETE | /api/files/{file} | files.destroy | App\Api\V1\Controllers\FileController@destroy          |

**Comment by redaoutamra** [comment]
still need help ?
