### ISSUE TITLE
Not able to migrate

### ISSUE THREAD

**Issue by georgesamaha1** [johndavedecano/laragym#88]
Compose install is running successfully
But when trying to run this command:  "PHP artisan migrate" I am getting this error: In PackageManifest.php line 122: Undefined index:  name
Please Help
![LaraGym](https://github.com/johndavedecano/laragym/assets/153836498/5d2ca54d-4f80-4b8a-b600-52afdb4bf38e)

**Comment by LONGHAIR1DUDE** [comment]
doing composer update solved this issue for me, but i get SQLSTATE errors instead now
