### ISSUE TITLE
Stuck on login page

### ISSUE THREAD

**Issue by HoriGazA** [johndavedecano/laragym#90]
After entering  email address and password, I got a successful login message even with a random email and password and was redirected back to the login page.

**Comment by johndavedecano** [comment]
any errors?

**Comment by HoriGaz** [comment]
![Screenshot from 2024-05-15 00-21-30](https://github.com/johndavedecano/laragym/assets/71996264/9ab04b4a-ad18-4bb3-9fda-bf1a9e64ddb5)

(node:15660) Warning: An error event has already been emitted on the socket. Please use the destroy method on the socket while handling a 'clientError' event.
(Use `node --trace-warnings ...` to show where the warning was created)

And the screen on php artisan serve always empty

**Comment by mauilyasa** [comment]
I have the same issue. How to access the dashboard? Its just get redirected to /login page again.

**Comment by HoriGaz** [comment]
So, i found that iam able to login when accessing using the localhost, but could not login (redirected back to login page) when using the server ip address

**Comment by johndavedecano** [comment]
@HoriGaz check if you see any error on the login response
