### ISSUE TITLE
Not getting production build

### ISSUE THREAD

**Issue by raptor0123** [johndavedecano/laragym#94]
![image](https://github.com/johndavedecano/laragym/assets/157416069/3d70e900-5631-424b-8540-41b0bbc31f32)

When I am giving the command for `vite build `the error comes in regards to wayland
![image](https://github.com/johndavedecano/laragym/assets/157416069/8a9d215a-e47b-4113-a95e-22a8b13ea2a7)

And when trying to build with `npm run build `

the error is 

![image](https://github.com/johndavedecano/laragym/assets/157416069/2f1c39fa-92e4-4d7b-b916-88049b2d4c7f)

**Comment by johndavedecano** [comment]
node version problem
