### ISSUE TITLE
COMPOSER INSTALL  PSR-4 autoloading standard

### ISSUE THREAD

**Issue by ben10thao** [johndavedecano/laragym#95]
During Composer Install

Class Tests\Feature\User\StatsControllerTest located in laragym-3.1.1/tests\Feature\StatsControllerTest.php does not comply with psr-4 autoloading standard. Skipping.

Please check on this. 

Renaming statscontrollertest.phpnamespace to tests\Feature\User seemed to work but frontend still ain't connecting to the backend

**Comment by johndavedecano** [comment]
I was wondering if you could send a PR to fix this?
